services:

  web:
    build: .
    container_name: TrackItNow-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/backend-app
    environment:
      database_name : "trackitnow-db"
      database_user : "admin"
      database_password : "password"
      database_host : "db"
      SECRET_KEY : "ff6caa249909d78c1bd427dd75aa9e5d21f7007e660b3afb60eea04f40608b23"
      PYTHONUNBUFFERED: "1"
  
  db:
    image: postgres:15
    container_name: postgres_db
    restart : always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "trackitnow-db"
    volumes:
     - postgres_data:/var/lib/postgresql/data
    
  
  redis:
    image: redis:7
    container_name: redis_cache
    restart : always
   

volumes:
  postgres_data: